### PR TITLE
Allow loading the mod when using Xaero Minimap Fairplay

### PR DESCRIPTION
**Pull request by Lucaslah**
When using the mod with Xaero Minimap Fair-play version the game would crash as the fair-play version has a different mod id

### CODE REVIEW

**Comment by rfresh2** [comment]
I intentionally don't want compatibility with the "fair-play" version, sorry.

Many of XP's features go against the spirit of the "fair" limitations. Don't use XP on servers where you're not allowed to use the normal minimap version.

**Comment by Lucaslah** [comment]
> I intentionally don't want compatibility with the "fair-play" version, sorry.
> 
> Many of XP's features go against the spirit of the "fair" limitations. Don't use XP on servers where you're not allowed to use the normal minimap version.

Maybe some way to disable the compatible version check then?

I get that  some of XP's features are not "fair" but I'm only using the feature that makes the nether map should the ground rather than the roof like the older versions, I know I could just use the full version (and disable the non fair features), but I use the FP version so I don't enable entity radar by mistake.

**Comment by rfresh2** [comment]
i'm not gonna disable the version check. But since XP is open source, you're technically free to fork and build whatever changes you want for yourself if you really want this.

> I know I could just use the full version (and disable the non fair features)

This is what I recommend. Not sure how you would enable radar by mistake?

**Comment by Lucaslah** [comment]
I meant like a config file or something to disable the version check (or a config option to enable compatibility with the fair-play version rather than disabling the version check).

> This is what I recommend. Not sure how you would enable radar by mistake?

Quite unlikely, but its just encase I enable any "non-fair" features by mistake when editing the config and don't realize it.

**Pull request closed without merging**
