### PR TITLE
Fabric 1.20.2

### PR DESCRIPTION
**Pull request by godkyo98**

### CODE REVIEW

**Comment by rfresh2** [comment]
Not sure what you've done to the git tree here lol

Just make 1 PR to fabric-1.20.1.

Sync your fork with current XaeroPlus repo. Then make a branch from fabric-1.20.1 and add your commit to it and PR that.

I'll handle forward committing it to all the other versions.

**Comment by godkyo98** [comment]
I don't know if I did something wrong somewhere. I just downloaded the
en_us version, translated it into vi_vn, and then uploaded it .At first it
was in patch 1, I felt it was a bit wrong so I changed it to 1.20.1. I
don't know if that bothers you or not.

Vào 05:50 CN, 14 Th1, 2024 rfresh2 ***@***.***> đã viết:

**Comment by rfresh2** [comment]
> I don't know if that bothers you or not.

Yeah i can't merge this as is. just take a look at the git diff here https://github.com/rfresh2/XaeroPlus/pull/100/files

you need to cancel all these PR's and resubmit one doing the steps as I described.

If you don't know how to do this I'll just make the commit for you if you send me the lang file on discord

**Comment by godkyo98** [comment]
So what can I delete and redo? If necessary, I will send you via discord
for convenience

Vào 06:42 CN, 14 Th1, 2024 rfresh2 ***@***.***> đã viết:

**Comment by rfresh2** [comment]
Here's an example of what I'd expect you to do in CLI commands:

`git checkout fabric-1.20.1`
`git reset origin/fabric-1.20.1 --hard`
\<add your lang file\>
`git add .`
`git commit -m "<commit msg here>"`
`git push -f`
\<create PR on github\>

**Comment by godkyo98** [comment]
Hello admin
Now I have made it to this step. What should I do next, admin?
[cid:2d366bbf-8e56-4620-a4f3-54a121c1e84e]
________________________________
Từ: rfresh2 ***@***.***>
Đã gửi: 14 Tháng Giêng 2024 07:05
Đến: rfresh2/XaeroPlus ***@***.***>
Cc: godkyo98 ***@***.***>; Author ***@***.***>
Chủ đề: Re: [rfresh2/XaeroPlus] Fabric 1.20.2 (PR #100)


Here's an example of what I'd expect you to do in CLI commands:

git checkout fabric-1.20.1
git reset origin/fabric-1.20.1 --hard
<add your lang file>
git add .
git commit -m "<commit msg here>"
git push -f
<create PR on github>

**Comment by godkyo98** [comment]
Admin, please read the email. If you need it, I'll send it over
Imgur: The magic of the Internet<https://imgur.com/a/86mKBi0>
________________________________
Từ: kyo kyo ***@***.***>
Đã gửi: 14 Tháng Giêng 2024 22:51
Đến: rfresh2/XaeroPlus ***@***.***>; rfresh2/XaeroPlus ***@***.***>
Cc: Author ***@***.***>
Chủ đề: Trả lời: [rfresh2/XaeroPlus] Fabric 1.20.2 (PR #100)

Hello admin
Now I have made it to this step. What should I do next, admin?
[cid:2d366bbf-8e56-4620-a4f3-54a121c1e84e]
________________________________
Từ: rfresh2 ***@***.***>
Đã gửi: 14 Tháng Giêng 2024 07:05
Đến: rfresh2/XaeroPlus ***@***.***>
Cc: godkyo98 ***@***.***>; Author ***@***.***>
Chủ đề: Re: [rfresh2/XaeroPlus] Fabric 1.20.2 (PR #100)


Here's an example of what I'd expect you to do in CLI commands:

git checkout fabric-1.20.1
git reset origin/fabric-1.20.1 --hard
<add your lang file>
git add .
git commit -m "<commit msg here>"
git push -f
<create PR on github>

**Comment by rfresh2** [comment]
eh I tried fixing your branch but github isn't letting me go the full way

Create a new PR from your branch: https://github.com/rfresh2/XaeroPlus/compare/fabric-1.20.1...godkyo98:XaeroPlus:fabric-1.20.1

Select the base branch as fabric-1.20.1

**Pull request closed without merging**
